i = 0
gen = 0
maxIt = 75
Gen0 = 150
nPop = 30
exponent = 3
sigma_initial = 0.7
sigma_final = 0.01
Cmin = 0.5
Cmax = 5
M = 0.15
nProc = 12

camberDirectory = 'Camber/airfoil_%i-%i.png'
plotsDirectory = 'Plots/airfoil_%i-%i.png'
xFoil_ResultsDirectory = 'Results_XFoil/Generation_%i/Specie_%i'
image_Extension = '/airfoil_%i-%i.png'
cfd_ResultsDirectory = 'Results_CFD/Generation_%i/Specie_%i'
xFoil_image = xFoil_ResultsDirectory + image_Extension
cfd_image = cfd_ResultsDirectory + image_Extension
